const sampleListings = [
  {
    title: "Secluded Beach House in Goa",
    description:
      "Escape to a secluded beach house on the Arabian coast. Surf, relax and rejuvenate.",
    image: "https://source.unsplash.com/400x300/?beach-house",
    price: 1800,
    location: "Goa",
    country: "India",
  },
  {
    title: "Mountain Cottage in Manali",
    description: "A peaceful retreat amidst snow-capped peaks.",
    image: "https://source.unsplash.com/400x300/?mountain-cottage",
    price: 2200,
    location: "Manali, HP",
    country: "India",
  },
  {
    title: "Luxury Villa in Jaipur",
    description: "A heritage villa with royal Rajasthani decor.",
    image: "https://source.unsplash.com/400x300/?villa",
    price: 3500,
    location: "Jaipur, RJ",
    country: "India",
  },
  {
    title: "Lake House in Udaipur",
    description: "Enjoy beautiful lake views in the city of lakes.",
    image: "https://source.unsplash.com/400x300/?lake-house",
    price: 2700,
    location: "Udaipur, RJ",
    country: "India",
  },
  {
    title: "Forest Bungalow in Rishikesh",
    description: "Stay amidst serene forests and rivers.",
    image: "https://source.unsplash.com/400x300/?forest",
    price: 2100,
    location: "Rishikesh, UK",
    country: "India",
  },
  {
    title: "Sunny Cottage in Puducherry",
    description: "Colorful French-style cottage near the beach.",
    image: "https://source.unsplash.com/400x300/?cottage",
    price: 1900,
    location: "Puducherry",
    country: "India",
  },
  {
    title: "Desert Tent in Jaisalmer",
    description: "An authentic Rajasthani desert camping experience.",
    image: "https://source.unsplash.com/400x300/?desert",
    price: 1600,
    location: "Jaisalmer, RJ",
    country: "India",
  },
  {
    title: "Snow Lodge in Leh",
    description: "Wake up to breathtaking Himalayan snow views.",
    image: "https://source.unsplash.com/400x300/?snow",
    price: 2800,
    location: "Leh, Ladakh",
    country: "India",
  },
  {
    title: "Hill View House in Ooty",
    description: "Panoramic hill views from your balcony.",
    image: "https://source.unsplash.com/400x300/?hill-house",
    price: 2300,
    location: "Ooty, TN",
    country: "India",
  },
  {
    title: "Farmstay in Coorg",
    description: "Experience coffee plantations and lush greenery.",
    image: "https://source.unsplash.com/400x300/?farm-house",
    price: 2500,
    location: "Coorg, KA",
    country: "India",
  },
  {
    title: "Backwater Villa in Alleppey",
    description: "Stay by the tranquil Kerala backwaters.",
    image: "https://source.unsplash.com/400x300/?backwater",
    price: 3000,
    location: "Alleppey, KL",
    country: "India",
  },
  {
    title: "Tea Estate Bungalow in Munnar",
    description: "Breathtaking tea garden views all around.",
    image: "https://source.unsplash.com/400x300/?tea-garden",
    price: 2400,
    location: "Munnar, KL",
    country: "India",
  },
  {
    title: "City Apartment in Mumbai",
    description: "Modern apartment with skyline views.",
    image: "https://source.unsplash.com/400x300/?apartment",
    price: 3200,
    location: "Mumbai, MH",
    country: "India",
  },
  {
    title: "Riverfront Lodge in Haridwar",
    description: "Stay by the holy Ganges river.",
    image: "https://source.unsplash.com/400x300/?river-lodge",
    price: 1800,
    location: "Haridwar, UK",
    country: "India",
  },
  {
    title: "Orchard House in Shimla",
    description: "Apple orchards surround this cozy home.",
    image: "https://source.unsplash.com/400x300/?orchard",
    price: 2600,
    location: "Shimla, HP",
    country: "India",
  },
  {
    title: "Island Villa in Andamans",
    description: "A villa steps away from crystal-clear waters.",
    image: "https://source.unsplash.com/400x300/?island-house",
    price: 3700,
    location: "Port Blair, AN",
    country: "India",
  },
  {
    title: "Rustic Cabin in Kodaikanal",
    description: "Escape to cool climate and misty hills.",
    image: "https://source.unsplash.com/400x300/?cabin",
    price: 2100,
    location: "Kodaikanal, TN",
    country: "India",
  },
  {
    title: "Beach Hut in Gokarna",
    description: "Sleep close to the sea with waves as your lullaby.",
    image: "https://source.unsplash.com/400x300/?beach-hut",
    price: 1500,
    location: "Gokarna, KA",
    country: "India",
  },
  {
    title: "Heritage Haveli in Jodhpur",
    description: "Royal blue city views and old-world charm.",
    image: "https://source.unsplash.com/400x300/?haveli",
    price: 2900,
    location: "Jodhpur, RJ",
    country: "India",
  },
  {
    title: "Rainforest Retreat in Wayanad",
    description: "Stay inside a lush rainforest.",
    image: "https://source.unsplash.com/400x300/?rainforest",
    price: 2200,
    location: "Wayanad, KL",
    country: "India",
  },
];
module.exports.sampleListings = sampleListings;
